version: "3.9"
services:

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  server:
    build:
      context: "./server"
      dockerfile: "Dockerfile.dev"
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
    volumes:
      - "/planning-poker-sercer/node_modules"
      - "./server:/planning-poker-server"
    env_file:
      - "./server/.env"

  client:
    stdin_open: true
    build:
      context: "./client"
      dockerfile: "Dockerfile.dev"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/planning-poker-client"
      - "/planning-poker-client/node_modules"
    env_file:
      - "./client/.env"
